### PR TITLE
Display vi mode in the toolbar

### PR DESCRIPTION
**Pull request by koljonen**

### CODE REVIEW

**Comment by j-bennet** [comment]
This is quite useful.

**Comment by amjith** [comment]
When I switch to vi mode from emacs mode it crashes with the following error message: 

```
  File "/Users/amjith/Dropbox/code/python/pgcli/pgcli/pgtoolbar.py", line 42, in get_toolbar_tokens
    result.append((token.On, '[F4] Vi-mode (' + _get_vi_mode(cli) + ')'))
  File "/Users/amjith/Dropbox/code/python/pgcli/pgcli/pgtoolbar.py", line 10, in _get_vi_mode
    InputMode.INSERT_MULTIPLE: 'M',
AttributeError: type object 'InputMode' has no attribute 'INSERT_MULTIPLE'
```

I'm using prompt-toolkit==1.0.7

**Comment by amjith** [comment]
I think this needs an upgrade of prompt-toolkit. After I upgraded from 1.0.7 to 1.0.9, this works fine. 

Let's bump the minimum version number for prompt_toolkit in setup.py.

**Comment by j-bennet** [comment]
Oh, good catch @amjith. I checked this PR with a new venv and it all worked for me. I'll bump it.
