### ISSUE TITLE
Newest python3-sqlparse breaks pgcli

### ISSUE THREAD

**Issue by Megatherium** [dbcli/pgcli#936]
## Description
After upgrading python3-sqlparse from 0.1.18-1 to 0.2.4-0.1~pgdg16.04+1 as soon as you enter select you get an exception. After that the program continues working but autocomplete is disabled.

`Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in runs-mode                                                                                                                                                                                                                
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 673, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/share/pgcli/pgcli/pgcompleter.py", line 238, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 100, in suggest_type
    full_text, identifier)
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 192, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'
`
## Your environment

`LinuxMint 18.3 Sylvia`
`Linux 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
`pgcli 0.20.1-3build1`

`apt-clone==0.2.1
apt-xapian-index==0.47
apturl==0.5.2
blinker==1.3
Brlapi==0.6.4
chardet==2.3.0
click==6.2
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
cryptography==1.2.3
defer==1.0.6
dirspec==13.10
greenlet==0.4.14
httplib2==0.9.1
idna==2.0
louis==2.6.4
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
msgpack==0.5.6
neovim==0.2.6
oauthlib==1.0.3
onboard==1.2.0
oneconf==0.3.9
pexpect==4.0.1
pgspecial==1.2.0
Pillow==3.1.2
piston-mini-client==0.7.5
prompt-toolkit==0.57
psutil==3.4.2
psycopg2==2.7.5
ptyprocess==0.5
pyasn1==0.1.9
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
Pygments==2.1
pygobject==3.20.0
PyICU==1.9.2
PyJWT==1.3.0
python-apt==1.1.0b1+ubuntu0.16.4.2
python-debian==0.1.27
python-xapp==1.0.0
pyxdg==0.25
reportlab==3.3.0
requests==2.9.1
screen-resolution-extra==0.0.0
sessioninstaller==0.0.0
setproctitle==1.1.8
six==1.10.0
sqlparse==0.2.4
system-service==0.3
thin-client-config-agent==0.8
ubuntu-drivers-common==0.0.0
ufw==0.35
urllib3==1.13.1
vboxapi==1.0
virtkey==0.63.0
wcwidth==0.1.6
xkit==0.0.0
`

**Comment by j-bennet** [comment]
It looks like you have a very old version of `pgcli` (0.20.1). This error does not happen with the latest version (1.10.3). Are you able to update (`pip install -U pgcli`)?

**Comment by Megatherium** [comment]
That actually did it (had to use --ignore-installed, etc.). Thank you very much.

**Comment by j-bennet** [comment]
Great!
