### ISSUE TITLE
Autocompleter explodes on last character from any valid SQL command or space for any other text

### ISSUE THREAD

**Issue by fernandocanizo** [dbcli/pgcli#567]
After starting `pgcli` typing any SQL command will blow auto-completer when last character is pressed. Or if any text is typed, it will blow after pressing `space`:

```
selectException in thread Thread-6:
Traceback (most recent call last):      
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()                          
  File "/usr/lib/python3.5/threading.py", line 862, in runs-mode                                                                                                             
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.5/site-packages/pgcli/pgcompleter.py", line 332, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/lib/python3.5/site-packages/pgcli/packages/sqlcompletion.py", line 104, in suggest_type
    stmt = SqlStatement(full_text, text_before_cursor)
  File "/usr/lib/python3.5/site-packages/pgcli/packages/sqlcompletion.py", line 66, in __init__
    self.identifier = parse_partial_identifier(word_before_cursor)
  File "/usr/lib/python3.5/site-packages/pgcli/packages/parseutils.py", line 299, in parse_partial_identifier
    elif p.token_next_match(0, Error, '"'):
AttributeError: 'Statement' object has no attribute 'token_next_match'
```

After this there's no more auto-completer and it doesn't explode anymore. Another example to show it's the same for any valid SQL:

```
dropException in thread Thread-4:
Traceback (most recent call last):       
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()                           
  File "/usr/lib/python3.5/threading.py", line 862, in runs-mode                                                                                                             
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 835, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.5/site-packages/pgcli/pgcompleter.py", line 332, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/lib/python3.5/site-packages/pgcli/packages/sqlcompletion.py", line 104, in suggest_type
    stmt = SqlStatement(full_text, text_before_cursor)
  File "/usr/lib/python3.5/site-packages/pgcli/packages/sqlcompletion.py", line 66, in __init__
    self.identifier = parse_partial_identifier(word_before_cursor)
  File "/usr/lib/python3.5/site-packages/pgcli/packages/parseutils.py", line 299, in parse_partial_identifier
    elif p.token_next_match(0, Error, '"'):
AttributeError: 'Statement' object has no attribute 'token_next_match'
```

$ pgcli --version
Version: 1.1.0

Running on Archlinux. If you need any other information don't hesitate to request it.

**Comment by darikg** [comment]
How did you install pgcli? It looks like maybe you have an incompatible version of sqlparse installed.

**Comment by fernandocanizo** [comment]
@darikg from [AUR](https://aur.archlinux.org/packages/pgcli/)

Tried with `pip` too but I got another error there and since the versions both methods install are the same, I didn't bother to report this problem:

```
$ pip-pypy install --user pgcli
Collecting pgcli
  Using cached pgcli-1.1.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pgspecial>=1.5.0 in ./.local/lib/pypy2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): click>=4.1 in ./.local/lib/pypy2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in ./.local/lib/pypy2.7/site-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): prompt_toolkit<1.1.0,>=1.0.0 in ./.local/lib/pypy2.7/site-packages (from pgcli)
Collecting psycopg2>=2.5.4 (from pgcli)
  Using cached psycopg2-2.6.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): sqlparse==0.1.19 in ./.local/lib/pypy2.7/site-packages (from pgcli)
Collecting configobj>=5.0.6 (from pgcli)
  Using cached configobj-5.0.6.tar.gz
Collecting humanize>=0.5.1 (from pgcli)
  Using cached humanize-0.5.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wcwidth>=0.1.6 in ./.local/lib/pypy2.7/site-packages (from pgcli)
Collecting setproctitle>=1.1.9 (from pgcli)
  Using cached setproctitle-1.1.10.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in ./.local/lib/pypy2.7/site-packages (from prompt_toolkit<1.1.0,>=1.0.0->pgcli)
Installing collected packages: psycopg2, configobj, humanize, setproctitle, pgcli
  Running setup.py install for psycopg2 ... error
    Complete output from command /usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qzRwXd/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WnwcXt-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/psycopg1.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-2.7/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-2.7/psycopg2
    creating build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_bugX000.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_notify.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_connection.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_cursor.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_with.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/testutils.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_green.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_module.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_psycopg2_dbapi20.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_types_extras.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_copy.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/dbapi20_tpc.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_lobject.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_dates.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_cancel.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_transaction.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_types_basic.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_extras_dictcursor.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_quote.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/testconfig.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_async.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_bug_gc.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/dbapi20.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    copying tests/test_errcodes.py -> build/lib.linux-x86_64-2.7/psycopg2/tests
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psycopg
    cc -O2 -fPIC -Wimplicit -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.6.2 (dt dec pq3 ext lo64)" -DPG_VERSION_HEX=0x090504 -DHAVE_LO64=1 -I/opt/pypy/include -I. -I/usr/include -I/usr/include/postgresql/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-2.7/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:38:0:
    ./psycopg/error.h:32:5: error: unknown type name ‘PyBaseExceptionObject’
         PyBaseExceptionObject exc;
         ^~~~~~~~~~~~~~~~~~~~~
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qzRwXd/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WnwcXt-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-qzRwXd/psycopg2/
```

Regarding `sqlparse`, got version 0.2.0:

```
$ pacman -Ss sqlparse
community/python-sqlparse 0.2.0-1 [installed]
    Non-validating SQL parser for Python
```

**Comment by darikg** [comment]
Ok sqlparse 0.20 is the issue. The master branch of pgcli supports it but v1.1.0 didn't. I don't know anything about archlinux or AUR--is it easy to swap sqlparse 0.19 for 0.20?

**Comment by j-bennet** [comment]
@darikg I think if you install 0.19 and pgcli has 0.20 in requirements, it won't start, will it?

**Comment by darikg** [comment]
@j-bennet I'm a little confused on that. The pgcli commit tagged v1.1.0 has sqlparse==0.1.19 listed in setup.py, so I don't understand how it ran in the first place.

**Comment by j-bennet** [comment]
Interesting. I dockerized pgcli on archlinux here:

https://github.com/j-bennet/dockerized/tree/master/pgcli-archlinux

I'm installing pgcli from master. I don't have the crash as described, but I see a different error when running pgcli:

```
[root@3b57e9b239ce pgcli]# pgcli -U postgres
ERROR:  type "hstore" does not exist at character 8
STATEMENT:  SELECT 'hstore'::regtype::oid
ERROR:  type "hstore" does not exist at character 8
STATEMENT:  SELECT 'hstore'::regtype::oid
Version: 1.1.0
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres@(none):postgres>
```

However, my pgcli was installed using pip, and that's different from @fernandocanizo. What's your arch linux version, @fernandocanizo ?

**Comment by fernandocanizo** [comment]
@darikg while Archlinux allows to install local versions using it's build system ABS, it's a little bit more effort. Since you told me sqlparse 0.20 was supported on master, I switched to package `pgcli-git` and it's solved for me now.

Thanks.

Maybe we should close this.

**Comment by fernandocanizo** [comment]
Well, it seems I talked a little bit too early :'(

Installing `pgcli-git`, which clones master branch, which it's supposes to support `sqlparse 0.20`, I get a worst behaviour:

```
 $ pgcli csw_webgis_test
Version: 1.1.0
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
flc@(none):csw_webgis_test> \d
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pgcli/main.py", line 773, in cli
    pgcli.run_cli()
  File "/usr/lib/python3.5/site-packages/pgcli/main.py", line 455, in run_cli
    watch_command, timing = special.get_watch_command(document.text)
AttributeError: module 'pgspecial' has no attribute 'get_watch_command'
```

Any command will spit the same error about `get_watch_command`.

And if I switch to `python-sqlparse-git` (which brings version: 0.1.18.32.g7b80406-1) I also get a bad behaviour, worst than previous I think:

```
$ pgcli mydb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pgcli/main.py", line 38, in <module>
    from pgspecial.main import (PGSpecial, NO_QUERY, content_exceeds_width)
  File "/usr/lib/python3.5/site-packages/pgspecial/__init__.py", line 12, in <module>
    from . import iocommands
  File "/usr/lib/python3.5/site-packages/pgspecial/iocommands.py", line 7, in <module>
    import sqlparse
ImportError: No module named 'sqlparse'
```

Both take me out to the bash shell, so of the three options, I'll stick with the first one which only leave me without auto-completion, but I still could use pgcli shell.

The third one may be due to something broken in Archlinux, but `pgcli-git` should work with `sqlparse 0.20`, right? And instead I get the `get_watch_command`error.

I'm thinking doing a local installation, building myself the package.

**Comment by amjith** [comment]
@fernandocanizo I'm very late to this party. But did you try installing directly from master using pip? 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by fernandocanizo** [comment]
@amjith Oh! That worked perfect :) I tried before pip, but not using github URL.

Thank you :)

**Comment by fernandocanizo** [comment]
Sorry @j-bennet I missed your question before: Archlinux is a rolling release distro, there's no such a thing as a _version_, most close thing I can tell you is that I installed it this week using ISO from 2016.08.01 and that it's updated to today.

**Comment by j-bennet** [comment]
Thanks @fernandocanizo, good to know - I've not worked with Archlinux before. I'm glad the problem was fixed by an install from master.

**Comment by darikg** [comment]
@amjith first-shots it of course

I'm still bewildered here. Looking at the AUR script [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pgcli) there's really not a lot happening -- it downloads `https://github.com/dbcli/pgcli/archive/v$pkgver.zip`, and then runs `setup.py`.  My only guess is it installed the correct version of sqlparse, but a newer version had already been installed system-wide?

cc @fzerorubigd who is listed as the package maintainer

**Comment by fernandocanizo** [comment]
@darikg I think no, but I'm not sure if I understood you correctly. This is a fresh install of Archlinux and there's no other package requiring `sqlparse`, by issuing a `dbcli` install with `yaourt` tool (a package manager for AUR) you get `sqlparse` as dependency. Did you intend to say that `setup.py` installed a local version of the dependency instead?

**Comment by fzerorubigd** [comment]
There is also a pgcli-git package in AUR (https://aur.archlinux.org/packages/pgcli-git/) . it build from the master branch. 
I use that version and there is no problem with that.

**Comment by fernandocanizo** [comment]
@fzerorubigd It didn't work for me, you can check the error I got some messages above (sorry, I didn't found a way to reference the proper message)

**Comment by amjith** [comment]
Please upgrade to v1.2.0. 

```
pip install -U pgcli
```

This issue is addressed in the new version.

**Comment by iv597** [comment]
Creating a virtualenv and pip-installing pgcli after uninstalling the AUR package "solves" the issue, but will require a shell script wrapper to switch to that venv every time I want to use pgcli. Doable, but far from optimal.

I'll look into patching up the PKGBUILD when I have some spare time, for us Arch folk.
